### PR TITLE
support for `execComands` - takes in list of commands for running in the started container

### PR DESCRIPTION
**Pull request by biswaroop1547**
new `execCommands` field present inside `service_object` is used to exec after a service container starts.

e.g:
```
...,
    "execCommands": [
        "psql -U postgres -d postgres -c 'CREATE EXTENSION vector;'"
    ],
...,
```

### CODE REVIEW

**Comment by filopedraz** [comment]
Great @biswaroop1547

**Comment by filopedraz** [comment]
@biswaroop1547 merged, but I suggest you add the key to the `ServiceResponse` schema as well

**Comment by biswaroop1547** [comment]
oh I totally missed that while reading the codebase looks llike, thanks! @filopedraz

**Comment by biswaroop1547** [comment]
here #74

**Pull request merged**
